### PR TITLE
fix(#1781): Handle promise rejections in CloudSQL samples

### LINKED ISSUE #1781: cloud-sql: Tests ignore unhandled promise rejections
I found this issue when adding a new check for #1745 . 
image
Unhandled rejections are also an issue with the App Engine Cloud SQL samples: 
https://source.cloud.google.com/results/invocations/f8c1a2e6-2247-478f-a4e1-0200c5f0f80c/targets/cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Fappengine%2Fnode8%2Fcloudsql_postgresql/log

It looks like the problem is that unhandled promise rejections still return a zero exit code, which is interpreted as a build success.

### PR DESCRIPTION
**Pull request by shubha-rajan**
fixes #1781

### CODE REVIEW

File: cloud-sql/postgres/knex/server.js [hunk 1]
```diff
@@ -182,7 +182,14 @@ app.get('/', (req, res) => {
       voteDiff: voteDiff,
       leaderMessage: leaderMessage,
     });
-  })();
+  }
+  catch(err) {
+    res
```
Comment (kurtisvg) [inline cloud-sql/postgres/knex/server.js:187]: nit: This error isn't being logged
