### PR TITLE
chore(monitoring/prometheus): Update prometheus to fix failing test

### LINKED ISSUE #2203: monitoring/prometheus: should be exposing metrics failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 33e9b601a98b3c03a0dbfc5a35d87d96774a6ad7
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/80ad3623-6fa5-4585-a1c8-5949d6af888f), [Sponge](http://sponge2/80ad3623-6fa5-4585-a1c8-5949d6af888f)
status: failed
<details><summary>Test output</summary><br><pre>expected 200 "OK", got 500 "Internal Server Error"
Error: expected 200 "OK", got 500 "Internal Server Error"
    at Context.<anonymous> (system-test/app.test.js:30:38)
    at processImmediate (internal/timers.js:456:21)
----
    at Test._assertStatus (node_modules/supertest/lib/test.js:296:12)
    at /tmpfs/src/github/nodejs-docs-samples/monitoring/prometheus/node_modules/supertest/lib/test.js:80:15
    at Test._assertFunction (node_modules/supertest/lib/test.js:311:11)
    at Test.assert (node_modules/supertest/lib/test.js:201:21)
    at Server.localAssert (node_modules/supertest/lib/test.js:159:12)
    at emitCloseNT (net.js:1654:8)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)</pre></details>

### PR DESCRIPTION
**Pull request by yuriatgoogle**
Fixes #2203 

Updating to work with prom-client v13.

### CODE REVIEW

File: monitoring/prometheus/app.js [hunk 1]
```diff
@@ -73,9 +75,13 @@ app.get('/', (req, res) => {
 });
 
 // [START monitoring_sli_metrics_prometheus_metrics_endpoint]
-app.get('/metrics', (req, res) => {
-  res.set('Content-Type', prometheus.register.contentType);
-  res.end(prometheus.register.metrics());
+app.get('/metrics', async (req, res) => {
+  try {
+    res.set('Content-Type', register.contentType);
+    res.end(await register.metrics());
```
Comment (ace-n) [inline monitoring/prometheus/app.js:81]: Tiny nit: @fhinkel is this appropriate, or would it be better to break the `await` into a separate line (to avoid confusion as to what `res.end` accepts)?

**Review by ace-n — APPROVED** [review]
LGTM if @fhinkel approves

File: monitoring/prometheus/app.js (hunk 1 above)
Comment (fhinkel) [reply monitoring/prometheus/app.js:81]: I think that's fine.

**Comment by fhinkel** [comment]
Rerunning the failing tests. Seems unrelated.

**Review by fhinkel — APPROVED** [review]

**Comment by yuriatgoogle** [comment]
It looks like `/run/helloworld` is failing and that's what blocking the merge... anything I could do about that? @fhinkel ?
